"""Change name to title in JobModel

Revision ID: c292faee879b
Revises: cfae5936c165
Create Date: 2024-02-01 12:26:32.833596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c292faee879b'
down_revision: Union[str, None] = 'cfae5936c165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('jobs', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('jobs', 'title')
    # ### end Alembic commands ###
